-- 1. Create categories table
create table public.categories (
    id bigint generated by default as identity primary key,
    name text not null unique,
    "order" integer not null default 0,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create products table
create table public.products (
    id bigint generated by default as identity primary key,
    title text not null,
    category text not null references public.categories(name) on update cascade on delete set null,
    price text not null,
    description text,
    image text,
    active boolean default true not null,
    promo boolean default false not null,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Insert initial categories
insert into public.categories (name, "order") values 
('DRINKS', 1),
('COPÃO', 2),
('LONG NECK', 3),
('LITRINHO', 4),
('LATÃO', 5),
('PORÇÕES', 6),
('HAMBURGUER', 7),
('OUTROS', 8)
on conflict do nothing;

-- 4. Set up Storage for images
insert into storage.buckets (id, name, public) 
values ('menu_images', 'menu_images', true)
on conflict do nothing;

-- 5. Row Level Security (RLS) Setup

-- Enable RLS on tables
alter table public.categories enable row level security;
alter table public.products enable row level security;

-- Categories Policies
create policy "Categories are viewable by everyone." 
on public.categories for select using (true);

create policy "Categories are modifiable by authenticated users only." 
on public.categories using (auth.role() = 'authenticated');

-- Products Policies
create policy "Products are viewable by everyone." 
on public.products for select using (true);

create policy "Products are modifiable by authenticated users only." 
on public.products using (auth.role() = 'authenticated');

-- Storage Policies
create policy "Images are viewable by everyone"
on storage.objects for select using (bucket_id = 'menu_images');

create policy "Images can be uploaded by authenticated users"
on storage.objects for insert with check (
  bucket_id = 'menu_images' and auth.role() = 'authenticated'
);

create policy "Images can be updated by authenticated users"
on storage.objects for update using (
  bucket_id = 'menu_images' and auth.role() = 'authenticated'
);

create policy "Images can be deleted by authenticated users"
on storage.objects for delete using (
  bucket_id = 'menu_images' and auth.role() = 'authenticated'
);
